services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_db:/var/lib/postgresql/data
    networks:
      - airflow_network

  airflow-webserver:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__FERNET_KEY=
      - JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
      - SPARK_HOME=/opt/spark
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./utils:/opt/airflow/utils
      - .:/opt/airflow
    ports:
      - "8080:8080"
    command: ["bash", "-c", "airflow db upgrade && airflow db init && airflow users create --username admin --password admin --firstname Airflow --lastname Admin --role Admin --email admin@example.com && airflow webserver && pip install -r /opt/airflow/requirements.txt"]
    networks:
      - airflow_network
    depends_on:
      - postgres

  airflow-scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
      - SPARK_HOME=/opt/spark
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./utils:/opt/airflow/utils
      - .:/opt/airflow
    command: ["bash", "-c", "pip install -r /opt/airflow/requirements.txt && airflow db upgrade && airflow scheduler"]
    networks:
      - airflow_network
    depends_on:
      - postgres
      - airflow-webserver

volumes:
  postgres_db:

networks:
  airflow_network:
    driver: bridge
